INSERT INTO DENTISTS
VALUES (1, 'Triin Tamm');
INSERT INTO DENTISTS
VALUES (2, 'Tiit Kääpa');
INSERT INTO DENTISTS
VALUES (3, 'Toomas Talu');
INSERT INTO DENTISTS
VALUES (4, 'Terje Tuulik');
INSERT INTO DENTISTS
VALUES (5, 'Tiiu Tasane');